[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tokamak_aggregator = "FQof46Y4b7ff7NnkdAAydmXnY6KvcZMwdJkLLwGStMpU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ming/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
